[package]
name = "MoneroRequest-Rust"
version = "0.1.0"
edition = "2021"
description = "MoneroRequest-Rust is an easy way to decode/encode monero-request codes in Rust."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
